# Define as fases de construção do ambiente
[phases.setup]
# Pede ao Railway para instalar pacotes do sistema Nix
# Isto garante que o Python e o yt-dlp estarão disponíveis
nixPkgs = ["python3", "yt-dlp"]

[phases.install]
cmds = ["npm install"]

[phases.start]
# Corrigido para apontar diretamente para o nosso ficheiro de servidor
cmd = "node server.js"

